export const CHANGE_EMAIL = 'AP/LoginPage/CHANGE_EMAIL'
export const CHANGE_PASSWORD = 'AP/LoginPage/CHANGE_PASSWORD'

export const POST_FORGOT_PASSWORD = 'AP/LoginPage/POST_FORGOT_PASSWORD'
export const POST_FORGOT_PASSWORD_SUCCESS =
  'AP/LoginPage/POST_FORGOT_PASSWORD_SUCCESS'
export const POST_FORGOT_PASSWORD_ERROR =
  'AP/LoginPage/POST_FORGOT_PASSWORD_ERROR'

export const CLEAR_DATA = 'AP/LoginPage/CLEAR_DATA'
